### ISSUE TITLE
Beatport is not working

### ISSUE THREAD

**Issue by nickshe89** [techdealer/plugin.audio.musicbox#19]
hello
you stop doing this add-on ?

thanks

**Comment by romanoh** [comment]
+1

**Comment by nickshe89** [comment]
beatport is not working can you fix it

**Comment by techdealer** [comment]
The fact that there were few updates in the last few months can be seen as a good thing: means that the addon uses relatively stable sources of content and on the other hand it reached a mature stage in development process. 

Beatport site was changed. The problem was fixed in the commit 877198f77202c62854f77a67d4a9489bc3af80b9

Thanks for report.

**Comment by nickshe89** [comment]
Not working again
